
public class Adjazenzmatrix{
 private Graph ADJ = new Graph(26);
 public void GraphErstellen(){
    ADJ.knotenEinfuegen(new Knoten(new Stadt("München",1430000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Ingolstadt",131000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Augsburg",281000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Regensburg",142000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Landshut",68000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Straubing",46000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Passau",50000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Garmisch-Partenkirchen",26000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Schwangau",3200)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Rosenheim",61000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Berchtesgaden",7800)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Eichstätt",13000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Regen",11000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Bodenmais",3300)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Freising",46000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Chiemsee", 0)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Tegernsee",3600)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Starnberg",23000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Burghausen",18000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("BadTölz",18000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Traunstein",19000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Altötting",13000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Schönau_am_Königssee",5400)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Ettal",800)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Kelheim",16000)));
    ADJ.knotenEinfuegen(new Knoten(new Stadt("Donaustauf",4000)));
    /*name(München) =M;
    name(Ingolstadt)=IN;
    name(Augsburg)=AU;
    name(Regensburg)=R;
    name(Landshut)=LA; 
    name(Straubing)=SR;
    name(Passau)=PA;
    name(Garmisch-Partenkirchen)=GAP;
    name(Schwangau)=SCW;
    name(Rosenheim)=ROS; 
    name(Berchtesgaden)=BEC;
    name(Eichstätt)=EIC;
    name(Regen)=REG;
    name(Bodenmais)=BOD;
    name(Freising)=FR;
    name(Chiemsee)=CH;
    name(Tegernsee)=TEG;
    name(Starnberg)=STA;
    name(Burghausen)=BUR;
    name(BadTölz)=TÖL;
    name(Traunstein)=TRT;
    name(Altötting)=AÖ;
    name(Schönau_am_Königssee)=KÖN;
    name(Ettal)=ETT;
    name(Kelheim)=KEL;
    name(Donaustauf)=DON;*/
    //Dieses für alle Städte 
    ADJ.kanteDefinierenSymmetrisch("M","IN",80);
    ADJ.kanteDefinierenSymmetrisch("M","AU",79);
    ADJ.kanteDefinierenSymmetrisch("M","R",124);
    ADJ.kanteDefinierenSymmetrisch("M","LA",72);
    ADJ.kanteDefinierenSymmetrisch("M","SR",141);
    ADJ.kanteDefinierenSymmetrisch("M","PA",192);
    ADJ.kanteDefinierenSymmetrisch("M","GAP",89);
    ADJ.kanteDefinierenSymmetrisch("M","SCW",118);
    ADJ.kanteDefinierenSymmetrisch("M","ROS",66);
    ADJ.kanteDefinierenSymmetrisch("M","BEC",154);
    ADJ.kanteDefinierenSymmetrisch("M","EIC",109);
    ADJ.kanteDefinierenSymmetrisch("M","REG",171);
    ADJ.kanteDefinierenSymmetrisch("M","BOD",179);
    ADJ.kanteDefinierenSymmetrisch("M","FR",40);
    ADJ.kanteDefinierenSymmetrisch("M","CH",87);
    ADJ.kanteDefinierenSymmetrisch("M","TEG",51);
    ADJ.kanteDefinierenSymmetrisch("M","STA",26);
    ADJ.kanteDefinierenSymmetrisch("M","BUR",113);
    ADJ.kanteDefinierenSymmetrisch("M","TÖL",51);
    ADJ.kanteDefinierenSymmetrisch("M","TRT",108);
    ADJ.kanteDefinierenSymmetrisch("M","AÖ",96);
    ADJ.kanteDefinierenSymmetrisch("M","KÖN",153);
    ADJ.kanteDefinierenSymmetrisch("M","ETT",85);
    ADJ.kanteDefinierenSymmetrisch("M","KEL",109);
    ADJ.kanteDefinierenSymmetrisch("M","DON",135);
    ADJ.kanteDefinierenSymmetrisch("IN","AU",84);
    ADJ.kanteDefinierenSymmetrisch("IN","R",98);
    ADJ.kanteDefinierenSymmetrisch("IN","LA",75);
    ADJ.kanteDefinierenSymmetrisch("IN","SR",140);
    ADJ.kanteDefinierenSymmetrisch("IN","PA",214);
    ADJ.kanteDefinierenSymmetrisch("IN","GAP",169);
    ADJ.kanteDefinierenSymmetrisch("IN","SCW",197);
    ADJ.kanteDefinierenSymmetrisch("IN","ROS",150);
    ADJ.kanteDefinierenSymmetrisch("IN","BEC",238);
    ADJ.kanteDefinierenSymmetrisch("IN","EIC",26);
    ADJ.kanteDefinierenSymmetrisch("IN","REG",170);
    ADJ.kanteDefinierenSymmetrisch("IN","BOD",178);
    ADJ.kanteDefinierenSymmetrisch("IN","FR",61);
    ADJ.kanteDefinierenSymmetrisch("IN","CH",171);
    ADJ.kanteDefinierenSymmetrisch("IN","TEG",135);
    ADJ.kanteDefinierenSymmetrisch("IN","STA",212);
    ADJ.kanteDefinierenSymmetrisch("IN","BUR",182);
    ADJ.kanteDefinierenSymmetrisch("IN","TÖL",135);
    ADJ.kanteDefinierenSymmetrisch("IN","TRT",192);
    ADJ.kanteDefinierenSymmetrisch("IN","AÖ",165);
    ADJ.kanteDefinierenSymmetrisch("IN","KÖN",236);
    ADJ.kanteDefinierenSymmetrisch("IN","ETT",165);
    ADJ.kanteDefinierenSymmetrisch("IN","KEL",58);
    ADJ.kanteDefinierenSymmetrisch("IN","DON",109);
    ADJ.kanteDefinierenSymmetrisch("AU","R",147);
    ADJ.kanteDefinierenSymmetrisch("AU","LA",123);
    ADJ.kanteDefinierenSymmetrisch("AU","SR",191);
    ADJ.kanteDefinierenSymmetrisch("AU","PA",243);
    ADJ.kanteDefinierenSymmetrisch("AU","GAP",152);
    ADJ.kanteDefinierenSymmetrisch("AU","SCW",101);
    ADJ.kanteDefinierenSymmetrisch("AU","ROS",149);
    ADJ.kanteDefinierenSymmetrisch("AU","BEC",236);
    ADJ.kanteDefinierenSymmetrisch("AU","EIC",72);
    ADJ.kanteDefinierenSymmetrisch("AU","REG",222);
    ADJ.kanteDefinierenSymmetrisch("AU","BOD",229);
    ADJ.kanteDefinierenSymmetrisch("AU","FR",91);
    ADJ.kanteDefinierenSymmetrisch("AU","CH",169);
    ADJ.kanteDefinierenSymmetrisch("AU","TEG",133);
    ADJ.kanteDefinierenSymmetrisch("AU","STA",80);
    ADJ.kanteDefinierenSymmetrisch("AU","BUR",181);
    ADJ.kanteDefinierenSymmetrisch("AU","TÖL",122);
    ADJ.kanteDefinierenSymmetrisch("AU","TRT",190);
    ADJ.kanteDefinierenSymmetrisch("AU","AÖ",163);
    ADJ.kanteDefinierenSymmetrisch("AU","KÖN",235);
    ADJ.kanteDefinierenSymmetrisch("AU","ETT",105);
    ADJ.kanteDefinierenSymmetrisch("AU","KEL",132);
    ADJ.kanteDefinierenSymmetrisch("AU","DON",186);
    ADJ.kanteDefinierenSymmetrisch("R","LA",66);
    ADJ.kanteDefinierenSymmetrisch("R","SR",47);
    ADJ.kanteDefinierenSymmetrisch("R","PA",121);
    ADJ.kanteDefinierenSymmetrisch("R","GAP",214);
    ADJ.kanteDefinierenSymmetrisch("R","SCW",243);
    ADJ.kanteDefinierenSymmetrisch("R","ROS",196);
    ADJ.kanteDefinierenSymmetrisch("R","BEC",283);
    ADJ.kanteDefinierenSymmetrisch("R","EIC",127);
    ADJ.kanteDefinierenSymmetrisch("R","REG",100);
    ADJ.kanteDefinierenSymmetrisch("R","BOD",98);
    ADJ.kanteDefinierenSymmetrisch("R","FR",88);
    ADJ.kanteDefinierenSymmetrisch("R","CH",216);
    ADJ.kanteDefinierenSymmetrisch("R","TEG",180);
    ADJ.kanteDefinierenSymmetrisch("R","STA",154);
    ADJ.kanteDefinierenSymmetrisch("R","BUR",141);
    ADJ.kanteDefinierenSymmetrisch("R","TÖL",181);
    ADJ.kanteDefinierenSymmetrisch("R","TRT",237);
    ADJ.kanteDefinierenSymmetrisch("R","AÖ",128);
    ADJ.kanteDefinierenSymmetrisch("R","KÖN",280);
    ADJ.kanteDefinierenSymmetrisch("R","ETT",211);
    ADJ.kanteDefinierenSymmetrisch("R","KEL",27);
    ADJ.kanteDefinierenSymmetrisch("R","DON",10);
    ADJ.kanteDefinierenSymmetrisch("LA","SR",68);
    ADJ.kanteDefinierenSymmetrisch("LA","PA",120);
    ADJ.kanteDefinierenSymmetrisch("LA","GAP",161);
    ADJ.kanteDefinierenSymmetrisch("LA","SCW",190);
    ADJ.kanteDefinierenSymmetrisch("LA","ROS",90);
    ADJ.kanteDefinierenSymmetrisch("LA","BEC",155);
    ADJ.kanteDefinierenSymmetrisch("LA","EIC",104);
    ADJ.kanteDefinierenSymmetrisch("LA","REG",98);
    ADJ.kanteDefinierenSymmetrisch("LA","BOD",106);
    ADJ.kanteDefinierenSymmetrisch("LA","FR",41);
    ADJ.kanteDefinierenSymmetrisch("LA","CH",96);
    ADJ.kanteDefinierenSymmetrisch("LA","TEG",127);
    ADJ.kanteDefinierenSymmetrisch("LA","STA",102);
    ADJ.kanteDefinierenSymmetrisch("LA","BUR",83);
    ADJ.kanteDefinierenSymmetrisch("LA","TÖL",128);
    ADJ.kanteDefinierenSymmetrisch("LA","TRT",110);
    ADJ.kanteDefinierenSymmetrisch("LA","AÖ",65);
    ADJ.kanteDefinierenSymmetrisch("LA","KÖN",159);
    ADJ.kanteDefinierenSymmetrisch("LA","ETT",158);
    ADJ.kanteDefinierenSymmetrisch("LA","KEL",62);
    ADJ.kanteDefinierenSymmetrisch("LA","DON",74);
    ADJ.kanteDefinierenSymmetrisch("SR","PA",82);
    ADJ.kanteDefinierenSymmetrisch("SR","GAP",217);
    ADJ.kanteDefinierenSymmetrisch("SR","SCW",245);
    ADJ.kanteDefinierenSymmetrisch("SR","ROS",160);
    ADJ.kanteDefinierenSymmetrisch("SR","BEC",171);
    ADJ.kanteDefinierenSymmetrisch("SR","EIC",169);
    ADJ.kanteDefinierenSymmetrisch("SR","REG",61);
    ADJ.kanteDefinierenSymmetrisch("SR","BOD",68);
    ADJ.kanteDefinierenSymmetrisch("SR","FR",129);
    ADJ.kanteDefinierenSymmetrisch("SR","CH",145);
    ADJ.kanteDefinierenSymmetrisch("SR","TEG",183);
    ADJ.kanteDefinierenSymmetrisch("SR","STA",157);
    ADJ.kanteDefinierenSymmetrisch("SR","BUR",93);
    ADJ.kanteDefinierenSymmetrisch("SR","TÖL",184);
    ADJ.kanteDefinierenSymmetrisch("SR","TRT",131);
    ADJ.kanteDefinierenSymmetrisch("SR","AÖ",87);
    ADJ.kanteDefinierenSymmetrisch("SR","KÖN",182);
    ADJ.kanteDefinierenSymmetrisch("SR","ETT",213);
    ADJ.kanteDefinierenSymmetrisch("SR","KEL",69);
    ADJ.kanteDefinierenSymmetrisch("SR","DON",41);
    ADJ.kanteDefinierenSymmetrisch("PA","GAP",275);
    ADJ.kanteDefinierenSymmetrisch("PA","SCW",310);
    ADJ.kanteDefinierenSymmetrisch("PA","ROS",162);
    ADJ.kanteDefinierenSymmetrisch("PA","BEC",148);
    ADJ.kanteDefinierenSymmetrisch("PA","EIC",243);
    ADJ.kanteDefinierenSymmetrisch("PA","REG",66);
    ADJ.kanteDefinierenSymmetrisch("PA","BOD",76);
    ADJ.kanteDefinierenSymmetrisch("PA","FR",162);
    ADJ.kanteDefinierenSymmetrisch("PA","CH",144);
    ADJ.kanteDefinierenSymmetrisch("PA","TEG",212);
    ADJ.kanteDefinierenSymmetrisch("PA","STA",222);
    ADJ.kanteDefinierenSymmetrisch("PA","BUR",77);
    ADJ.kanteDefinierenSymmetrisch("PA","TÖL",213);
    ADJ.kanteDefinierenSymmetrisch("PA","TRT",122);
    ADJ.kanteDefinierenSymmetrisch("PA","AÖ",81);
    ADJ.kanteDefinierenSymmetrisch("PA","KÖN",148);
    ADJ.kanteDefinierenSymmetrisch("PA","ETT",278);
    ADJ.kanteDefinierenSymmetrisch("PA","KEL",144);
    ADJ.kanteDefinierenSymmetrisch("PA","DON",115);
    ADJ.kanteDefinierenSymmetrisch("GAP","SCW",61);
    ADJ.kanteDefinierenSymmetrisch("GAP","ROS",106);
    ADJ.kanteDefinierenSymmetrisch("GAP","BEC",193);
    ADJ.kanteDefinierenSymmetrisch("GAP","EIC",197);
    ADJ.kanteDefinierenSymmetrisch("GAP","REG",259);
    ADJ.kanteDefinierenSymmetrisch("GAP","BOD",267);
    ADJ.kanteDefinierenSymmetrisch("GAP","FR",129);
    ADJ.kanteDefinierenSymmetrisch("GAP","CH",127);
    ADJ.kanteDefinierenSymmetrisch("GAP","TEG",74);
    ADJ.kanteDefinierenSymmetrisch("GAP","STA",76);
    ADJ.kanteDefinierenSymmetrisch("GAP","BUR",215);
    ADJ.kanteDefinierenSymmetrisch("GAP","TÖL",56);
    ADJ.kanteDefinierenSymmetrisch("GAP","TRT",147);
    ADJ.kanteDefinierenSymmetrisch("GAP","AÖ",198);
    ADJ.kanteDefinierenSymmetrisch("GAP","KÖN",192);
    ADJ.kanteDefinierenSymmetrisch("GAP","ETT",15);
    ADJ.kanteDefinierenSymmetrisch("GAP","KEL",198);
    ADJ.kanteDefinierenSymmetrisch("GAP","DON",223);
    ADJ.kanteDefinierenSymmetrisch("SCW","ROS",132);
    ADJ.kanteDefinierenSymmetrisch("SCW","BEC",219);
    ADJ.kanteDefinierenSymmetrisch("SCW","EIC",201);
    ADJ.kanteDefinierenSymmetrisch("SCW","REG",288);
    ADJ.kanteDefinierenSymmetrisch("SCW","BOD",295);
    ADJ.kanteDefinierenSymmetrisch("SCW","FR",157);
    ADJ.kanteDefinierenSymmetrisch("SCW","CH",153);
    ADJ.kanteDefinierenSymmetrisch("SCW","TEG",100);
    ADJ.kanteDefinierenSymmetrisch("SCW","STA",80);
    ADJ.kanteDefinierenSymmetrisch("SCW","BUR",247);
    ADJ.kanteDefinierenSymmetrisch("SCW","TÖL",83);
    ADJ.kanteDefinierenSymmetrisch("SCW","TRT",174);
    ADJ.kanteDefinierenSymmetrisch("SCW","AÖ",229);
    ADJ.kanteDefinierenSymmetrisch("SCW","KÖN",218);
    ADJ.kanteDefinierenSymmetrisch("SCW","ETT",48);
    ADJ.kanteDefinierenSymmetrisch("SCW","KEL",226);
    ADJ.kanteDefinierenSymmetrisch("SCW","DON",252);
    ADJ.kanteDefinierenSymmetrisch("ROS","BEC",99);
    ADJ.kanteDefinierenSymmetrisch("ROS","EIC",177);
    ADJ.kanteDefinierenSymmetrisch("ROS","REG",240);
    ADJ.kanteDefinierenSymmetrisch("ROS","BOD",248);
    ADJ.kanteDefinierenSymmetrisch("ROS","FR",109);
    ADJ.kanteDefinierenSymmetrisch("ROS","CH",22);
    ADJ.kanteDefinierenSymmetrisch("ROS","TEG",42);
    ADJ.kanteDefinierenSymmetrisch("ROS","STA",89);
    ADJ.kanteDefinierenSymmetrisch("ROS","BUR",102);
    ADJ.kanteDefinierenSymmetrisch("ROS","TÖL",59);
    ADJ.kanteDefinierenSymmetrisch("ROS","TRT",52);
    ADJ.kanteDefinierenSymmetrisch("ROS","AÖ",84);
    ADJ.kanteDefinierenSymmetrisch("ROS","KÖN",96);
    ADJ.kanteDefinierenSymmetrisch("ROS","ETT",102);
    ADJ.kanteDefinierenSymmetrisch("ROS","KEL",178);
    ADJ.kanteDefinierenSymmetrisch("ROS","DON",204);
    ADJ.kanteDefinierenSymmetrisch("BEC","EIC",260);
    ADJ.kanteDefinierenSymmetrisch("BEC","REG",209);
    ADJ.kanteDefinierenSymmetrisch("BEC","BOD",223);
    ADJ.kanteDefinierenSymmetrisch("BEC","FR",192);
    ADJ.kanteDefinierenSymmetrisch("BEC","CH",72);
    ADJ.kanteDefinierenSymmetrisch("BEC","TEG",125);
    ADJ.kanteDefinierenSymmetrisch("BEC","STA",172);
    ADJ.kanteDefinierenSymmetrisch("BEC","BUR",79);
    ADJ.kanteDefinierenSymmetrisch("BEC","TÖL",133);
    ADJ.kanteDefinierenSymmetrisch("BEC","TRT",50);
    ADJ.kanteDefinierenSymmetrisch("BEC","AÖ",88);
    ADJ.kanteDefinierenSymmetrisch("BEC","KÖN",5);
    ADJ.kanteDefinierenSymmetrisch("BEC","ETT",185);
    ADJ.kanteDefinierenSymmetrisch("BEC","KEL",271);
    ADJ.kanteDefinierenSymmetrisch("BEC","DON",287);
    ADJ.kanteDefinierenSymmetrisch("EIC","REG",198);
    ADJ.kanteDefinierenSymmetrisch("EIC","BOD",206);
    ADJ.kanteDefinierenSymmetrisch("EIC","FR",86);
    ADJ.kanteDefinierenSymmetrisch("EIC","CH",199);
    ADJ.kanteDefinierenSymmetrisch("EIC","TEG",163);
    ADJ.kanteDefinierenSymmetrisch("EIC","STA",137);
    ADJ.kanteDefinierenSymmetrisch("EIC","BUR",210);
    ADJ.kanteDefinierenSymmetrisch("EIC","TÖL",163);
    ADJ.kanteDefinierenSymmetrisch("EIC","TRT",220);
    ADJ.kanteDefinierenSymmetrisch("EIC","AÖ",192);
    ADJ.kanteDefinierenSymmetrisch("EIC","KÖN",264);
    ADJ.kanteDefinierenSymmetrisch("EIC","ETT",193);
    ADJ.kanteDefinierenSymmetrisch("EIC","KEL",66);
    ADJ.kanteDefinierenSymmetrisch("EIC","DON",136);
    ADJ.kanteDefinierenSymmetrisch("REG","BOD",12);
    ADJ.kanteDefinierenSymmetrisch("REG","FR",140);
    ADJ.kanteDefinierenSymmetrisch("REG","CH",177);
    ADJ.kanteDefinierenSymmetrisch("REG","TEG",225);
    ADJ.kanteDefinierenSymmetrisch("REG","STA",200);
    ADJ.kanteDefinierenSymmetrisch("REG","BUR",125);
    ADJ.kanteDefinierenSymmetrisch("REG","TÖL",226);
    ADJ.kanteDefinierenSymmetrisch("REG","TRT",163);
    ADJ.kanteDefinierenSymmetrisch("REG","AÖ",119);
    ADJ.kanteDefinierenSymmetrisch("REG","KÖN",212);
    ADJ.kanteDefinierenSymmetrisch("REG","ETT",256);
    ADJ.kanteDefinierenSymmetrisch("REG","KEL",122);
    ADJ.kanteDefinierenSymmetrisch("REG","DON",93);
    ADJ.kanteDefinierenSymmetrisch("BOD","FR",147);
    ADJ.kanteDefinierenSymmetrisch("BOD","CH",184);
    ADJ.kanteDefinierenSymmetrisch("BOD","TEG",133);
    ADJ.kanteDefinierenSymmetrisch("BOD","STA",207);
    ADJ.kanteDefinierenSymmetrisch("BOD","BUR",132);
    ADJ.kanteDefinierenSymmetrisch("BOD","TÖL",234);
    ADJ.kanteDefinierenSymmetrisch("BOD","TRT",171);
    ADJ.kanteDefinierenSymmetrisch("BOD","AÖ",126);
    ADJ.kanteDefinierenSymmetrisch("BOD","KÖN",226);
    ADJ.kanteDefinierenSymmetrisch("BOD","ETT",263);
    ADJ.kanteDefinierenSymmetrisch("BOD","KEL",122);
    ADJ.kanteDefinierenSymmetrisch("BOD","DON",93);
    ADJ.kanteDefinierenSymmetrisch("FR","CH",130);
    ADJ.kanteDefinierenSymmetrisch("FR","TEG",93);
    ADJ.kanteDefinierenSymmetrisch("FR","STA",67);
    ADJ.kanteDefinierenSymmetrisch("FR","BUR",108);
    ADJ.kanteDefinierenSymmetrisch("FR","TÖL",94);
    ADJ.kanteDefinierenSymmetrisch("FR","TRT",151);
    ADJ.kanteDefinierenSymmetrisch("FR","AÖ",90);
    ADJ.kanteDefinierenSymmetrisch("FR","KÖN",196);
    ADJ.kanteDefinierenSymmetrisch("FR","ETT",124);
    ADJ.kanteDefinierenSymmetrisch("FR","KEL",86);
    ADJ.kanteDefinierenSymmetrisch("FR","DON",112);
    ADJ.kanteDefinierenSymmetrisch("CH","TEG",63);
    ADJ.kanteDefinierenSymmetrisch("CH","STA",110);
    ADJ.kanteDefinierenSymmetrisch("CH","BUR",61);
    ADJ.kanteDefinierenSymmetrisch("CH","TÖL",80);
    ADJ.kanteDefinierenSymmetrisch("CH","TRT",32);
    ADJ.kanteDefinierenSymmetrisch("CH","AÖ",60);
    ADJ.kanteDefinierenSymmetrisch("CH","KÖN",76);
    ADJ.kanteDefinierenSymmetrisch("CH","ETT",129);
    ADJ.kanteDefinierenSymmetrisch("CH","KEL",199);
    ADJ.kanteDefinierenSymmetrisch("CH","DON",225);
    ADJ.kanteDefinierenSymmetrisch("TEG","STA",64);
    ADJ.kanteDefinierenSymmetrisch("TEG","BUR",130);
    ADJ.kanteDefinierenSymmetrisch("TEG","TÖL",19);
    ADJ.kanteDefinierenSymmetrisch("TEG","TRT",84);
    ADJ.kanteDefinierenSymmetrisch("TEG","AÖ",135);
    ADJ.kanteDefinierenSymmetrisch("TEG","KÖN",129);
    ADJ.kanteDefinierenSymmetrisch("TEG","ETT",70);
    ADJ.kanteDefinierenSymmetrisch("TEG","KEL",163);
    ADJ.kanteDefinierenSymmetrisch("TEG","DON",189);
    ADJ.kanteDefinierenSymmetrisch("STA","BUR",153);
    ADJ.kanteDefinierenSymmetrisch("STA","TÖL",44);
    ADJ.kanteDefinierenSymmetrisch("STA","TRT",132);
    ADJ.kanteDefinierenSymmetrisch("STA","AÖ",135);
    ADJ.kanteDefinierenSymmetrisch("STA","KÖN",176);
    ADJ.kanteDefinierenSymmetrisch("STA","ETT",71);
    ADJ.kanteDefinierenSymmetrisch("STA","KEL",135);
    ADJ.kanteDefinierenSymmetrisch("STA","DON",161);
    ADJ.kanteDefinierenSymmetrisch("BUR","TÖL",138);
    ADJ.kanteDefinierenSymmetrisch("BUR","TRT",45);
    ADJ.kanteDefinierenSymmetrisch("BUR","AÖ",14);
    ADJ.kanteDefinierenSymmetrisch("BUR","KÖN",82);
    ADJ.kanteDefinierenSymmetrisch("BUR","ETT",213);
    ADJ.kanteDefinierenSymmetrisch("BUR","KEL",142);
    ADJ.kanteDefinierenSymmetrisch("BUR","DON",135);
    ADJ.kanteDefinierenSymmetrisch("TÖL","TRT",92);
    ADJ.kanteDefinierenSymmetrisch("TÖL","AÖ",140);
    ADJ.kanteDefinierenSymmetrisch("TÖL","KÖN",137);
    ADJ.kanteDefinierenSymmetrisch("TÖL","ETT",52);
    ADJ.kanteDefinierenSymmetrisch("TÖL","KEL",168);
    ADJ.kanteDefinierenSymmetrisch("TÖL","DON",194);
    ADJ.kanteDefinierenSymmetrisch("TRT","AÖ",47);
    ADJ.kanteDefinierenSymmetrisch("TRT","KÖN",54);
    ADJ.kanteDefinierenSymmetrisch("TRT","ETT",144);
    ADJ.kanteDefinierenSymmetrisch("TRT","KEL",22);
    ADJ.kanteDefinierenSymmetrisch("TRT","DON",174);
    ADJ.kanteDefinierenSymmetrisch("AÖ","KÖN",91);
    ADJ.kanteDefinierenSymmetrisch("AÖ","ETT",196);
    ADJ.kanteDefinierenSymmetrisch("AÖ","KEL",125);
    ADJ.kanteDefinierenSymmetrisch("AÖ","DON",129);
    ADJ.kanteDefinierenSymmetrisch("KÖN","ETT",188);
    ADJ.kanteDefinierenSymmetrisch("KÖN","KEL",265);
    ADJ.kanteDefinierenSymmetrisch("KÖN","DON",291);
    ADJ.kanteDefinierenSymmetrisch("ETT","KEL",194);
    ADJ.kanteDefinierenSymmetrisch("ETT","DON",219);
    ADJ.kanteDefinierenSymmetrisch("KEL","DON",38);
    //Dieses für alle Einträge der Matrix
    
    System.out.println("ADJ");
    ADJ.adjazenzmatrixAusgeben();
    System.out.println();
    System.out.println("Indizes");
    System.out.println("0: München");
    System.out.println("1: Ingolstadt");
    System.out.println("2: Augsburg");
    System.out.println("3: Regensburg");
    System.out.println("4: Landshut");
    System.out.println("5: Straubing");
    System.out.println("6: Passau");
    System.out.println("7: Garmisch-Partenkirchen");
    System.out.println("8: Schwangau");
    System.out.println("9: Rosenheim");
    System.out.println("10: Berchtesgaden");
    System.out.println("11: Eichstätt");
    System.out.println("12: Regen");
    System.out.println("13: Bodenmais");
    System.out.println("14: Freising");
    System.out.println("15: Chiemsee");
    System.out.println("16: Tegernsee");
    System.out.println("17: Starnberg");
    System.out.println("18: Burghausen");
    System.out.println("19: Bad Tölz");
    System.out.println("20: Traunstein");
    System.out.println("21: Altötting");
    System.out.println("22: Schönau am Königssee");
    System.out.println("23: Ettal");
    System.out.println("24: Kelheim");
    System.out.println("25: Donaustauf");
    //Dieses für alle Städte
    }
    
    public Graph matrixGeben() {
        return ADJ;
    }
}